
spring:
  profiles: order-service-test
server:
  port: 8086
eureka:
  client:
    service-url:
      default-Zone: http://localhost:8761/eureka
    enabled: true
    fetch-registry: true


------------------------

spring:
  profiles: order-service-prd
server:
  port: 8082
eureka:
  client:
    service-url:
      default-Zone: http://localhost:8761/eureka
    enabled: true
    fetch-registry: true

