spring:
  profiles: user-service-dev
hello: abc

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

  
  

   
spring:
  profiles: user-service-pro
  
hello: 521ww

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
